### ISSUE TITLE
The Validation acc of the dataset of Cora

### ISSUE THREAD

**Issue by Kazaf-Lee** [NSLab-CUK/Community-aware-Graph-Transformer#1]
Hi, thank you for providing this research. When I was replicating the code recently, I found that when the k step transistion of your Cora dataset was set to 3, the maximum acc of the epoch validation was only 78. Is there anything wrong with my setting?

**Comment by Kazaf-Lee** [comment]
Best Val Epoch: 189, Best Val Acc: 0.7763, Test Acc: 0.7412, F1_test: 0.7412 This is part of the result. Is this result normal?

**Comment by hoangvanthuy90** [comment]
Hello, It may come from the parameters.  Please config your hyper-parameters well.
Also, please take a look at this configuration.
![image](https://github.com/NSLab-CUK/Community-aware-Graph-Transformer/assets/12929461/54385246-3912-4c38-8505-44b7d20bbfeb)

**Comment by Kazaf-Lee** [comment]
Appreciate a lot for your answer, I will try again.
